In [2]:
import pandas as pd
a=pd.read_csv('/content/train.csv')
print(a)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7
1              1021     1          0.5         1   0       1          53
2               563     1          0.5         1   2       1          41
3               615     1          2.5         0   0       0          10
4              1821     1          1.2         0  13       1          44
...             ...   ...          ...       ...  ..     ...         ...
1995            794     1          0.5         1   0       1           2
1996           1965     1          2.6         1   0       0          39
1997           1911     0          0.9         1   1       1          36
1998           1512     0          0.9         0   4       1          46
1999            510     1          2.0         1   5       1          45

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7
1       0.7        136        3  ...        905      1988  2631    17     3
2       0.9        145        5  ...       1263      1716  2603    11     2
3       0.8        131        6  ...       1216      1786  2769    16     8
4       0.6        141        2  ...       1208      1212  1411     8     2
...     ...        ...      ...  ...        ...       ...   ...   ...   ...
1995    0.8        106        6  ...       1222      1890   668    13     4
1996    0.2        187        4  ...        915      1965  2032    11    10
1997    0.7        108        8  ...        868      1632  3057     9     1
1998    0.1        145        5  ...        336       670   869    18    10
1999    0.9        168        6  ...        483       754  3919    19     4

      talk_time  three_g  touch_screen  wifi  price_range
0            19        0             0     1            1
1             7        1             1     0            2
2             9        1             1     0            2
3            11        1             0     0            2
4            15        1             1     0            1
...         ...      ...           ...   ...          ...
1995         19        1             1     0            0
1996         16        1             1     1            2
1997          5        1             1     0            3
1998         19        1             1     1            0
1999          2        1             1     1            3

[2000 rows x 21 columns]

In [3]:
y=a['price_range']
print(y)

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [4]:
x=a.drop('price_range',axis=1)
print(x)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7
1              1021     1          0.5         1   0       1          53
2               563     1          0.5         1   2       1          41
3               615     1          2.5         0   0       0          10
4              1821     1          1.2         0  13       1          44
...             ...   ...          ...       ...  ..     ...         ...
1995            794     1          0.5         1   0       1           2
1996           1965     1          2.6         1   0       0          39
1997           1911     0          0.9         1   1       1          36
1998           1512     0          0.9         0   4       1          46
1999            510     1          2.0         1   5       1          45

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2   2         20       756  2549     9     7
1       0.7        136        3   6        905      1988  2631    17     3
2       0.9        145        5   6       1263      1716  2603    11     2
3       0.8        131        6   9       1216      1786  2769    16     8
4       0.6        141        2  14       1208      1212  1411     8     2
...     ...        ...      ...  ..        ...       ...   ...   ...   ...
1995    0.8        106        6  14       1222      1890   668    13     4
1996    0.2        187        4   3        915      1965  2032    11    10
1997    0.7        108        8   3        868      1632  3057     9     1
1998    0.1        145        5   5        336       670   869    18    10
1999    0.9        168        6  16        483       754  3919    19     4

      talk_time  three_g  touch_screen  wifi
0            19        0             0     1
1             7        1             1     0
2             9        1             1     0
3            11        1             0     0
4            15        1             1     0
...         ...      ...           ...   ...
1995         19        1             1     0
1996         16        1             1     1
1997          5        1             1     0
1998         19        1             1     1
1999          2        1             1     1

[2000 rows x 20 columns]

In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
xtrain_norm=scaler.fit_transform(x)
print(xtrain_norm)

[[0.22778891 0.         0.68       ... 0.         0.         1.        ]
 [0.34736139 1.         0.         ... 1.         1.         0.        ]
 [0.04141617 1.         0.         ... 1.         1.         0.        ]
 ...
 [0.94188377 0.         0.16       ... 1.         1.         0.        ]
 [0.6753507  0.         0.16       ... 1.         1.         1.        ]
 [0.00601202 1.         0.6        ... 1.         1.         1.        ]]

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.05, random_state=0)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
1979           1614     0          1.2         0   1       1           9
1273            627     1          1.6         1   3       1          12
538             704     0          2.2         1   4       0          53
1529           1831     1          2.2         1   4       0          55
37             1725     1          1.6         1   6       1           6
...             ...   ...          ...       ...  ..     ...         ...
835            1224     1          1.6         0   9       0          33
1216           1158     0          0.7         1   1       1          29
1653           1190     0          2.0         1   0       0          40
559            1191     0          2.4         1   2       0          13
684             706     0          0.5         0  13       1          31

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
1979    0.1        161        3   2        173      1219  1832    15     8
1273    0.2        131        7  17        447       819  2476    17     1
538     0.2        186        6   6        251      1013  3653     7     1
1529    1.0        189        8   9       1693      1790  1133    14     3
37      0.5        119        2  18        609      1307  3429     6     5
...     ...        ...      ...  ..        ...       ...   ...   ...   ...
835     1.0        157        1  18        522       563  3796    10     5
1216    0.7        123        2  20        311      1796  1542    17     9
1653    0.2         93        5   1       1399      1646  3610    13     7
559     0.9        169        1   7        179      1813  1028    14     6
684     0.1        108        3  19        543       938  2419     8     7

      talk_time  three_g  touch_screen  wifi
1979         11        1             0     0
1273         10        1             0     0
538          15        1             1     1
1529         10        0             1     0
37            4        1             1     0
...         ...      ...           ...   ...
835          13        1             1     0
1216         15        1             0     1
1653          9        0             0     1
559           8        1             1     1
684           4        1             0     1

[1900 rows x 20 columns]
      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
405            1454     1          0.5         1   1       0          34
1190           1092     1          0.5         1  10       0          11
1132           1524     1          1.8         1   0       0          10
731            1807     1          2.1         0   2       0          49
1754           1086     1          1.7         1   0       1          43
...             ...   ...          ...       ...  ..     ...         ...
1999            510     1          2.0         1   5       1          45
1927           1023     1          0.7         0   2       1          63
80             1589     1          0.6         1   0       1          58
1854           1571     0          2.9         0   1       0          30
264            1722     0          2.6         0   8       0          18

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
405     0.7         83        4   3        250      1033  3419     7     5
1190    0.5        167        3  14        468       571   737    14     4
1132    0.6        174        4   1        154       550  2678    16     5
731     0.8        125        1  10        337      1384  1906    17    13
1754    0.2        111        6   1         56      1150  3285    11     5
...     ...        ...      ...  ..        ...       ...   ...   ...   ...
1999    0.9        168        6  16        483       754  3919    19     4
1927    0.7        153        7   8        367      1985  3155    11    10
80      0.9         85        7   7        319      1206  3464    19    10
1854    0.9        150        7   3        805       956   586    10     9
264     0.8        177        2  16        865      1741  3271    14     0

      talk_time  three_g  touch_screen  wifi
405           5        1             1     0
1190         11        0             1     0
1132         13        1             0     1
731          13        0             1     1
1754         17        1             1     0
...         ...      ...           ...   ...
1999          2        1             1     1
1927          7        1             1     1
80            6        1             1     1
1854          4        0             1     1
264          15        1             0     1

[100 rows x 20 columns]
1979    1
1273    1
538     2
1529    1
37      3
       ..
835     3
1216    1
1653    3
559     0
684     1
Name: price_range, Length: 1900, dtype: int64
405     3
1190    0
1132    2
731     2
1754    2
       ..
1999    3
1927    3
80      3
1854    0
264     3
Name: price_range, Length: 100, dtype: int64

In [7]:
import pandas as pd
a=pd.read_csv('/content/heart.csv')
print(a)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal  target
0        0   0     1       1
1        0   0     2       1
2        2   0     2       1
3        2   0     2       1
4        2   0     2       1
..     ...  ..   ...     ...
298      1   0     3       0
299      1   0     3       0
300      1   2     3       0
301      1   1     3       0
302      1   1     2       0

[303 rows x 14 columns]

In [8]:
y=a['target']
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [9]:
x=a.drop('target',axis=1)
print(x)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal
0        0   0     1
1        0   0     2
2        2   0     2
3        2   0     2
4        2   0     2
..     ...  ..   ...
298      1   0     3
299      1   0     3
300      1   2     3
301      1   1     3
302      1   1     2

[303 rows x 13 columns]

In [10]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
xtrain_norm=scaler.fit_transform(x)
print(xtrain_norm)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.05, random_state=0)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
97    52    1   0       108   233    1        1      147      0      0.1
90    48    1   2       124   255    1        1      175      0      0.0
198   62    1   0       120   267    0        1       99      1      1.8
103   42    1   2       120   240    1        1      194      0      0.8
22    42    1   0       140   226    0        1      178      0      0.0
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
251   43    1   0       132   247    1        0      143      1      0.1
192   54    1   0       120   188    0        1      113      0      1.4
117   56    1   3       120   193    0        0      162      0      1.9
47    47    1   2       138   257    0        0      156      0      0.0
172   58    1   1       120   284    0        0      160      0      1.8

     slope  ca  thal
97       2   3     3
90       2   2     2
198      1   2     3
103      0   0     3
22       2   0     2
..     ...  ..   ...
251      1   4     3
192      1   1     3
117      1   0     3
47       2   0     2
172      1   0     2

[287 rows x 13 columns]
     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
225   70    1   0       145   174    0        1      125      1      2.6
152   64    1   3       170   227    0        0      155      0      0.6
228   59    1   3       170   288    0        0      159      0      0.2
201   60    1   0       125   258    0        0      141      1      2.8
52    62    1   2       130   231    0        1      146      0      1.8
245   48    1   0       124   274    0        0      166      0      0.5
175   40    1   0       110   167    0        0      114      1      2.0
168   63    1   0       130   254    0        0      147      0      1.4
223   56    0   0       200   288    1        0      133      1      4.0
217   63    1   0       130   330    1        0      132      1      1.8
111   57    1   2       150   126    1        1      173      0      0.2
135   49    0   0       130   269    0        1      163      0      0.0
218   65    1   0       135   254    0        0      127      0      2.8
12    49    1   1       130   266    0        1      171      0      0.6
15    50    0   2       120   219    0        1      158      0      1.6
66    51    1   2       100   222    0        1      143      1      1.2

     slope  ca  thal
225      0   0     3
152      1   0     3
228      1   0     3
201      1   1     3
52       1   3     3
245      1   0     3
175      1   0     3
168      1   1     3
223      0   2     3
217      2   3     3
111      2   1     3
135      2   0     2
218      1   1     3
12       2   0     2
15       1   0     2
66       1   0     2
97     1
90     1
198    0
103    1
22     1
      ..
251    0
192    0
117    1
47     1
172    0
Name: target, Length: 287, dtype: int64
225    0
152    1
228    0
201    0
52     1
245    0
175    0
168    0
223    0
217    0
111    1
135    1
218    0
12     1
15     1
66     1
Name: target, dtype: int64

In [14]:
import pandas as pd
df=pd.read_csv('/content/heart.csv')
print(df)
df.columns
y=df['target']#target
x=df[['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach','exang', 'oldpeak', 'slope', 'ca', 'thal']]#features
#min max scaling:
from sklearn.preprocessing import MinMaxScaler
scalar=MinMaxScaler()#normalized
scalar.fit(x)
x_scaled=scalar.transform(x)
print(x_scaled)
from sklearn.model_selection import train_test_split
x=df.drop('target',axis=1)
y=df['target']
x_scaled_train, x_scaled_test, y_train, y_test = train_test_split(x, y,test_size=0.2,random_state=10)
#chceking the shape of orginal data
df.shape
#shape of traing and testing data
print(x_scaled_train.shape)
print(x_scaled_test.shape)
print(y_train.shape)
print(y_test.shape)
col=df.columns
for i in col:
  print(df[i])
import random
y_p=[]
def perceptron(weights,bias):
    for i in range(len(x_scaled_test)):
        z = np.dot(weights,x_scaled_test.iloc[i]) + bias
        s = 1 / (1 + np.exp(-z))
        if s>=0.5:
          y_p.append(1)
        else:
          y_p.append(0)
    return y_p

# Initialize random weights and bias
random.seed(42)  # For reproducibility
weights = [random.uniform(-1, 1) for _ in range(len(x_scaled_test.columns))]
bias = random.uniform(-1, 1)
y_p = perceptron(weights,bias)
print(y_p)
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_p)
print("Accuracy",accuracy)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal  target
0        0   0     1       1
1        0   0     2       1
2        2   0     2       1
3        2   0     2       1
4        2   0     2       1
..     ...  ..   ...     ...
298      1   0     3       0
299      1   0     3       0
300      1   2     3       0
301      1   1     3       0
302      1   1     2       0

[303 rows x 14 columns]
[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]
(242, 13)
(61, 13)
(242,)
(61,)
0      63
1      37
2      41
3      56
4      57
       ..
298    57
299    45
300    68
301    57
302    57
Name: age, Length: 303, dtype: int64
0      1
1      1
2      0
3      1
4      0
      ..
298    0
299    1
300    1
301    1
302    0
Name: sex, Length: 303, dtype: int64
0      3
1      2
2      1
3      1
4      0
      ..
298    0
299    3
300    0
301    0
302    1
Name: cp, Length: 303, dtype: int64
0      145
1      130
2      130
3      120
4      120
      ...
298    140
299    110
300    144
301    130
302    130
Name: trestbps, Length: 303, dtype: int64
0      233
1      250
2      204
3      236
4      354
      ...
298    241
299    264
300    193
301    131
302    236
Name: chol, Length: 303, dtype: int64
0      1
1      0
2      0
3      0
4      0
      ..
298    0
299    0
300    1
301    0
302    0
Name: fbs, Length: 303, dtype: int64
0      0
1      1
2      0
3      1
4      1
      ..
298    1
299    1
300    1
301    1
302    0
Name: restecg, Length: 303, dtype: int64
0      150
1      187
2      172
3      178
4      163
      ...
298    123
299    132
300    141
301    115
302    174
Name: thalach, Length: 303, dtype: int64
0      0
1      0
2      0
3      0
4      1
      ..
298    1
299    0
300    0
301    1
302    0
Name: exang, Length: 303, dtype: int64
0      2.3
1      3.5
2      1.4
3      0.8
4      0.6
      ...
298    0.2
299    1.2
300    3.4
301    1.2
302    0.0
Name: oldpeak, Length: 303, dtype: float64
0      0
1      0
2      2
3      2
4      2
      ..
298    1
299    1
300    1
301    1
302    1
Name: slope, Length: 303, dtype: int64
0      0
1      0
2      0
3      0
4      0
      ..
298    0
299    0
300    2
301    1
302    1
Name: ca, Length: 303, dtype: int64
0      1
1      2
2      2
3      2
4      2
      ..
298    3
299    3
300    3
301    3
302    2
Name: thal, Length: 303, dtype: int64
0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Accuracy 0.5573770491803278